version: '3.8'

services:

  glusterfs:
    image: gluster/gluster-centos:latest
    container_name: glusterfs
    volumes:
      - gluster-data:/var/lib/glusterd
      - gluster-config:/etc/glusterfs
      - gluster-log:/var/log/glusterfs
    ports:
      - "24007:24007"
      - "24008:24008"
      - "49152:49152" 
    restart: unless-stopped

  moodle:
    image: bitnami/moodle:4.4.0
    ports:
      - "8100:8080"
    volumes:
      - moodledata:/bitnami/moodle

  nginx:
    image: nginx:latest
    container_name: nginxtest
    volumes:
      - ./nginx-certbot/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www:/var/www/certbot/
    ports:
      - "80:80"
      - "443:443"

  certbot:
    image: certbot/certbot:latest
    container_name: certbottest
    volumes:
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf:/etc/letsencrypt/
    command: >
      sh -c "
      echo '* * * 25 * certbot renew --nginx --noninteractive --post-hook \"nginx -s reload\"' > /etc/crontabs/root &&
      crond -f
      "
      
  tgbot:
    build:
      context: ./bot
    restart: always
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN} 
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: always
    
  cpuram_monitor:
    image: alpine:latest
    volumes:
      - ./script/cpuram.sh:/cpuram.sh
      - ./logs:/var/log      
    command: sh -c "
      apk add --no-cache procps gawk &&
      chmod +x /cpuram.sh &&  
      /cpuram.sh" 
    restart: unless-stopped
    
volumes:
  moodledata:
  grafana-data: