---
- name: Установка нгинкса и сертбота по таймеру в контейнере
  hosts: localhost
  become:  yes
  tasks:
  
    - name: Запуск докера
      service:
        name: docker
        state: started
        enabled: yes
      
    - name: Создаём директорию для проекта
      file:
        path: /home/user/docker
        state: directory

    - name: Создание docker-compose.yml
      copy: 
        dest: /home/user/docker/docker-compose.yml
        content: |
         version: '3.8'
         services:
           nginx: 
             image: nginx:latest
             container_name: nginx
             volumes:
               - ./nginx.conf:/etc/nginx/nginx.conf:ro
               - ./certbot/conf:/etc/letsencrypt/	
               - ./certbot/www:/var/www/certbot
             ports:
               - "80:80"
               - "443:443"	
           certbot:
             image: certbot/certbot
             container_name: certbot
             volumes:
               - ./certbot/www:/var/www/certbot
               - ./certbot/conf:/etc/letsencrypt/
             command:  >
                sh -c "
                echo '* * 25 * * certbot renew --nginx --noninteractive --post-hook \"nginx -s reload\"' > /etc/crontabs/root &&
                crond -f
                "
             depends_on:
               - nginx
     
    - name: Перенос конфига для nginx'a
      copy:
        src: ./nginx.conf
        dest: /home/user/docker/nginx.conf
        
    - name: Создание необходимых директорий для Certbot'a
      file:
        path: "{{item}}"
        state: directory
        mode: 0755
      loop:
        - /home/user/docker/html
        - /home/user/docker/certbot/conf
        - /home/user/docker/certbot/www
        
    - name: Сборка контейнера
      community.docker.docker_compose_v2:
        project_src: /home/user/docker/

    - name: Проверка доступности домена
      uri:
        url: "http://pobeda.ypa.com/.well-known/acme-challenge/test"
        return_content: yes
        status_code: 404
      register: domain_check
      ignore_errors: yes
      
    - name: Получение сертификата без драй ран
      ansible.builtin.shell: 
        cmd: 
          docker-compose run --rm certbot certonly --webroot --webroot-path /var/www/certbot -d pobeda.ypa.com --email mymail@example.com --agree-tos --no-eff-email --noninteractive
        chdir: /home/user/docker/
    
    - name: Рестарт нгинкса
      ansible.builtin.shell:
        cmd: docker-compose restart nginx
        chdir: /home/user/docker/ 
        