name: CI/CD 

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Clone tgbot repo
        run: git clone https://github.com/moryaz/tgbot ./bot

      - name: Build bot image
        run: docker build -t weather_bot ./bot

      - name: Start all services
        run: |
          TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }} \
          WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} \
          docker-compose up -d
          
      - name: Check Status
        run: docker compose ps